### ISSUE TITLE
BUG:Transaction Dates Display as null under Savings & Loan Transactions

### ISSUE THREAD

**Issue by airsay** [openMF/community-app#3206] opened 2020-05-10 13:26 UTC
## Description
When a transaction occurs (under any type of savings account: fixed deposit, recurring deposit or regular savings account), the date displays as null under transactions tab. Drilling down by clicking on the transaction however shows the correct date

## Steps to Reproduce

Create any Savings/Fixed Deposit/Recurring Deposit Product.
Create a Client
For the above created client, Create a Savings/Fixed Deposit/Recurring Deposit ACCOUNT for that client.
Perform a transaction on that account (such as a deposit, withdrawal or calculate and post interest)

## Expected Behaviour

Date on which transaction occurred should by correctly displayed under Transactions Tab in the Clients Account
## Settings

- Mifos X version: Fineract (develop)
- Browser used: Firefox 75.0 (64-bit), Chromium 77.0.3856.0 (Developer Build) (64-bit), Microsoft Edge Version 83.0.478.28 (Official build) beta (64-bit)
- OS: Windows 10
- Tomcat: 9.0.34
- JDK: Oracle JDK 11.0.7
-MySQL:5.5.62

## Screenshots

Transaction Tab view
![image](https://user-images.githubusercontent.com/7488892/81500425-0dc0a700-92ca-11ea-8b3d-70fd1a7d1761.png)

Drill down of transaction ID 2 from above (showing correct date)

![image](https://user-images.githubusercontent.com/7488892/81500447-2f219300-92ca-11ea-871c-d10564c86622.png)

**Comment by angelboxes** [comment] 2020-07-15 18:27
Hi, this issue is caused by the changes made in the issue #3196. Since in the original issue it doesn't specify which pages were the ones with the problem or has any attached screenshots and I don't own a computer with Safari browser I'm not pretty sure if this was a Safari issue at all. Can I be assigned to this issue?

**Comment by bharathcgowda** [comment] 2020-09-24 13:01
Hi @angelboxes , We have noticed the issue on the loan transaction screen as well. this does not look like a browser issue, would you be able to take a look at this issue still?

**Comment by francisguchie** [comment] 2020-12-10 20:07
This is the case for Loan Transactions Tab too

**Comment by francisguchie** [comment] 2020-12-11 15:20
Some dates show and others do not 
Loan transactions do not show dates 
Yet Loan Repayment Schedule Shows 

![image](https://user-images.githubusercontent.com/22683654/101920732-0f39b100-3bc4-11eb-8221-2bd1edf53f30.png)

Loan Repayment Schedule

![image](https://user-images.githubusercontent.com/22683654/101921012-663f8600-3bc4-11eb-985d-894faaac8667.png)

**Comment by francisguchie** [comment] 2020-12-11 15:31
> Hi, this issue is caused by the changes made in the issue #3196. Since in the original issue it doesn't specify which pages were the ones with the problem or has any attached screenshots and I don't own a computer with Safari browser I'm not pretty sure if this was a Safari issue at all. Can I be assigned to this issue?

IMHO 
the fix #3196 needs to be re-visited

**Comment by bharathcgowda** [comment] 2021-05-01 08:49
closing this ticket as the issue is already fixed
![image](https://user-images.githubusercontent.com/65952533/116776820-3ff18880-aa88-11eb-96c0-a5e66e6f091e.png)

**Closed as completed by bharathcgowda** 2021-05-01 08:49 UTC
