### ISSUE TITLE
Unable  to approve share account which is already submitted. 

### ISSUE THREAD

**Issue by santoshconflux** [openMF/community-app#2951] opened 2018-05-09 13:45 UTC
Try to approve following share account.

https://staging.openmf.org/#/shareaccount/20/approve

username/password : mifos/password

**Comment by Nenge1** [comment] 2018-05-09 14:33
@santoshfinflux , this is a duplicate of the issue [issue #2948](https://github.com/openMF/community-app/issues/2948)

**Comment by ShruthiRajaram** [comment] 2018-11-09 12:33
@santoshconflux  I was able to approve the application. Can you retest and close if issue is resolved?

**Comment by abiyats** [comment] 2018-11-09 12:58
This fix has worked for me. I have checked it.

**Comment by abiyats** [comment] 2018-11-09 13:04
Dear All,

I have found the fix here.

https://github.com/openMF/community-app/pull/2982/files


Regards,
Abiy A.

**Comment by jonathanzhang53** [comment] 2018-11-24 15:21
@luckyman20 This is also one of the fixed issues that is GCI task.

**Comment by luckyman20** [comment] 2018-11-24 15:33
@jonathanzhang53 Took the task down, thanks for informing.

@santoshconflux Can we close this issue now?

**Closed as completed** 2018-12-14 07:18 UTC
Labels: bug, gci, p1_MifosRelease, gsoc, blocker, Hacktoberfest, cg4w

**Comment by saifromeo** [comment] 2020-10-08 10:47
where do I get the 19.12 release? Neither do I see branch, nor tag, pls help
