### ISSUE TITLE
Reskin - "Terms" field and "Repaid every" field in loan application have the same function

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2069] opened 2017-03-08 11:21 UTC
On the loan application form the field "Terms" and "Repaid every" have the same functionality, i think we need one  between them.

Create product by Admin -> Products -> Loan product -> Create
Create loan account to an active client
On the loan application form 

![terms-repaid](https://cloud.githubusercontent.com/assets/8160209/23702020/8b4b89d0-040a-11e7-8aa3-dd48acbf64c9.png)

**Comment by DanCarl857** [comment] 2017-03-09 08:03
Let me look into this

**Comment by DanCarl857** [comment] 2017-03-09 08:06
Are you saying we should remove on of them? I really don't get what the issue is

**Comment by santoshmath** [comment] 2017-03-09 08:11
Check the  screenshot here: how it should look like.
![demo](https://cloud.githubusercontent.com/assets/23022667/23741352/180a131e-04ce-11e7-94a7-94f1528a36ea.png)

**Comment by MexinaD** [comment] 2017-03-09 08:22
@DanCarl857 they have the same functionality, so i suggest one should be removed (I prefer "Repaied every" to remain)

**Comment by DanCarl857** [comment] 2017-03-10 06:54
@santoshmath should I do as @MexinaD has suggested?

**Comment by santoshmath** [comment] 2017-03-10 07:30
@DanCarl857 , Yes, and the order of the fields must be like in one . I shared screenshot in comment

**Comment by iamsk9** [comment] 2017-03-11 12:25
@MexinaD @santoshmath I made changes to remove the fields besides Terms in loan application.
Now it looks like this:

![screenshot 19](https://cloud.githubusercontent.com/assets/10477029/23823211/c22e8990-0683-11e7-8d99-d80574c9bbea.png)

I created a PR referencing this issue. Please review it. [#2082](https://github.com/openMF/community-app/pull/2082)

**Comment by mbj36** [comment] 2017-03-15 14:17
@santoshmath retest and close it

**Comment by santoshmath** [comment] 2017-03-16 04:13
Tested it on 16/3/2017 on new_reskin branch. This issue is resolved. @MexinaD , I am closing this, let me know if you think any issue related to it.

**Closed by santoshmath** 2017-03-16 04:13 UTC
Labels: bug, p1, reskin
