### ISSUE TITLE
MIFOS-2173: Unable to select products in product mix

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1639] opened 2016-11-12 20:45 UTC
In Admin -> Products -> Product Mix
Unable to create new product mix as it is not possible to select any products from the allowed product list to move to the restricted products list. 

Moved over from https://mifosforge.jira.com/browse/MIFOSX-2173
![75](https://cloud.githubusercontent.com/assets/823454/20240785/e5a4baae-a8d5-11e6-9f72-d5b16ee204ac.png)

**Comment by shubhsingh594** [comment] 2016-11-18 04:33
hi all,
Can i work on this bug ?

**Comment by mbj36** [comment] 2016-12-26 12:36
@edcable @nazeer1100126  I can't reproduce this issue in demo server. Is it solved ? Should we close the issue ?

**Comment by nazeer1100126** [comment] 2016-12-26 12:43
@mbj36 This issue was fixed by GCI student. PR details are https://github.com/openMF/community-app/pull/1701. We found a critical issue in work flow after updating demo server. Had to update the servers with that critical fix. So https://github.com/openMF/community-app/pull/1701 code also part of this new update..
You can close this issue. But there is another issue from platform side where edit product mix throwing some exception. You can add that new issue as part of GCI.

**Comment by mbj36** [comment] 2016-12-26 12:45
Thanks for the update :)

**Closed by mbj36** 2016-12-26 12:45 UTC
Labels: bug, gci, mifosforge
