### ISSUE TITLE
Reskin: missing icons on various pages 

### ISSUE THREAD

**Issue by anu-007** [openMF/community-app#2120] opened 2017-03-20 14:26 UTC
icons on various pages are missing like under admin>system and  check inbox and task page.

**Comment by aditodkar** [comment] 2017-03-20 14:31
How can I reproduce the issue @anu-007

**Comment by anu-007** [comment] 2017-03-20 15:45
@aditodkar just run community-app on localhost login with id/password -(mifos/password) , click admin from the navbar and select system from the drop down a page will open up you will find missing icons on that page also you will find missing icons on "check inbox and task"  page on side nav

**Comment by santoshmath** [comment] 2017-03-21 08:11
@anu-007 , could you share screenshots here?

**Comment by santoshmath** [comment] 2017-03-23 04:24
Without Reskin:

![demo](https://cloud.githubusercontent.com/assets/23022667/24232088/8e6cf554-0fae-11e7-8c2e-3cfe008079d8.png)

With Reskin: Icons are missing for Manage Reports and Scheduler Jobs

![reskin](https://cloud.githubusercontent.com/assets/23022667/24232106/aec80686-0fae-11e7-9cea-1f1e822b2121.png)

**Comment by santoshmath** [comment] 2017-03-23 04:29
Hi @anu-007 , If icons are missing in multiple pages then we need to create checklist like this. #2126 . I am also searching for such missing icons and let me know if you found them.

**Comment by Agnessy** [comment] 2017-03-23 14:02
@santoshmath Reskin:In Organisation, It looks like Bulk Loan Reassignment icon and Manage Funds icon are alike.

**Comment by mbj36** [comment] 2017-03-23 16:39
Noticed @Agnessy

**Comment by ThisuraThejith** [comment] 2017-03-26 06:03
I will work on this.

**Comment by skprabhanjan** [comment] 2017-04-12 13:13
@mbj36 , @anu-007  and @santoshmath Is this fixed.? if not can I work on this.?
Thanks:)

**Comment by ThisuraThejith** [comment] 2017-04-12 13:39
This issue is not present in new_reskin branch.

**Comment by mbj36** [comment] 2017-05-03 20:38
@santoshmath checkout and close it

**Comment by santoshmath** [comment] 2017-05-04 06:20
Tested it on 4/5/2017 on new_reskin branch and this issue is fixed.

**Closed by santoshmath** 2017-05-04 06:20 UTC
Labels: design, gsoc, p2, reskin

**Comment by Agnessy** [comment] 2017-09-11 14:00
@mbj36 @santoshmath  I see Admin > Organisation > Bulk Loan Reassignment icon and Manage Funds icon are still alike .

**Comment by Agnessy** [comment] 2017-09-12 08:38
@mbj36 @santoshmath  I see Admin > Organisation > Bulk Loan Reassignment icon and Manage Funds icon are still alike .
