### ISSUE TITLE
Web Cam Issue 

### ISSUE THREAD

**Issue by VampireNaeem** [openMF/community-app#3131] opened 2019-11-14 10:19 UTC
The following error occured:  DOMException: Could not start video source
Steps to Reproduce
1)Sign in to mifos
https://demo.openmf.org/#/

Credentials:
Username: mifos
Password: password

2) Go to clients from top nav bar
3)Click any client
4)On the left below the image,Click on Camera icon

Expected Behaviour
It show allow the user to take the picture through laptop Camera

Actual Behaviour
It show error in console 

"The following error occured:  DOMException: Could not start video source"

## Screenshots
=
![Capture](https://user-images.githubusercontent.com/33661602/68848423-20c73580-06f2-11ea-9fff-8deab9dfa8be.PNG)

**Comment by awasum** [comment] 2019-11-15 09:17
This is caused by URL.createObjectURL been deprecated in Chrome or Firefox.
See: 
https://stackoverflow.com/questions/51101408/deprecation-of-createobjecturl-and-replace-with-the-new-htmlmediaelement-srcobje
https://github.com/jonashartmann/webcam-directive/pull/74
https://github.com/jonashartmann/webcam-directive/issues/77

We can solve this by updating  webcam-directive to version: "3.2.1" in bower.json

Let me send a quick PR for this.

**Comment by awasum** [comment] 2019-11-15 09:27
@VampireNaeem  check the PR: https://github.com/openMF/community-app/pull/3134

**Comment by awasum** [comment] 2019-11-15 15:32
PR #3134 merged. Closing this.

**Closed as completed by awasum** 2019-11-15 15:32 UTC
Labels: bug, p1_MifosRelease
