### ISSUE TITLE
Side nav is not scrolling with the page  in firefox browser

### ISSUE THREAD

**Issue by gkrishnan724** [openMF/community-app#1787] opened 2016-12-29 14:13 UTC
As you scroll down the page in community-app, the side-nav remains on top which should not happen.
![screenshot from 2016-12-29 19-39-24](https://cloud.githubusercontent.com/assets/21004514/21545560/aa3e6cfa-cdfe-11e6-97dd-5b180cbbbd39.png)

This could be observed in the following link:
(https://demo.openmf.org/reskin/#/users/)

**Comment by mbj36** [comment] 2017-01-12 13:01
I am not able to reproduce it, it working fine for me @gkrishnan724

**Comment by gkrishnan724** [comment] 2017-01-16 12:21
@mbj36 I just checked it out, it is still there.
go to this page (https://demo.openmf.org/reskin/#/users/) and scroll down, you will observe that the nav-bar is not fixed it disappears as you get to the bottom of the page.

**Comment by mbj36** [comment] 2017-01-16 13:48
@gkrishnan724 It's browser problem, it see it working fine in chrome but not working in firefox

**Comment by gkrishnan724** [comment] 2017-01-16 14:34
@mbj36 Ok, I'll mention that in the issue thanks :)

**Comment by mbj36** [comment] 2017-01-24 16:24
@gkrishnan724 Reskin is merged

**Comment by gkrishnan724** [comment] 2017-03-10 12:43
@mbj36 can you close this? its fixed.

**Closed** 2017-05-10 04:07 UTC
Labels: design, gsoc, p2, reskin
