### ISSUE TITLE
MIFOSX-2562: Not able to create user if external service configuration is not proper

### ISSUE THREAD

**Issue by mbj36** [openMF/community-app#1657] opened 2016-11-22 22:59 UTC
Steps to reproduce:
1. Click on Admin -> System -> External Service -> External Service -> Edit and modify the following parameter
username: support@cloudmicrofinance.com modify as support1@cloudmicrofinance.com.
and save the page.
2. Now Click on Admin -> users -> Create new user with valid inputs,
Not able to save create user page. Displayed error message as "error.msg.user.email.invalid".
though valid email id is entered.
Proper error message of external service configuration should be displayed.

**Comment by santoshmath** [comment] 2017-11-13 11:01
Duplicate of https://github.com/openMF/community-app/issues/1724

**Closed by santoshmath** 2017-11-13 11:01 UTC
Labels: enhancement, gci, mifosforge
