### ISSUE TITLE
Reskin - No field to edit nominal interest rate and interest method during loan application

### ISSUE THREAD

**Issue by MexinaD** [openMF/community-app#2067] opened 2017-03-08 11:08 UTC
After creation of loan product where you can supply minimum, default and maximum value of interest rate.
There is no feature in the loan application to edit the interest rate to the choice of the user.

**Comment by santoshmath** [comment] 2017-03-09 08:16
Hi @mbj36 , this is one of the critical issue. Check the  screenshot how it looks like:

![demo](https://cloud.githubusercontent.com/assets/23022667/23741525/d2881e02-04ce-11e7-9c25-9f955908591d.png)

**Comment by DanCarl857** [comment] 2017-03-09 08:21
@santoshmath please could you give me some directions on how to reproduce this? The loan application page am looking at doesn't look anything like the one above and I just updated my repo.
I would like to fix this

**Comment by MexinaD** [comment] 2017-03-09 08:27
@DanCarl857 
You can reproduce this in new_reskin repo by navigate to Client -> View client -> New Loan
The form to apply loan does not have a place to edit interest rate and interest method (The picture above is the page found in community-app which has "nominal interest rate" and "interest method")

**Comment by santoshmath** [comment] 2017-03-09 08:30
@DanCarl857 , Create any loan product.>>Create a client>> Then go to client page>>and click on 'New Loan' .The next page would look like below where Nominal Interest Rate is missing. (compare with  my previous comment screenshot)

![reskin](https://cloud.githubusercontent.com/assets/23022667/23741902/ae4a97f2-04d0-11e7-8021-77655665dcb9.png)

**Comment by santoshmath** [comment] 2017-03-09 08:30
And also Interest Method is not displaying , next to nominal interest rate

**Comment by DanCarl857** [comment] 2017-03-10 06:55
Ok @santoshmath let me look at that

**Comment by iamsk9** [comment] 2017-03-11 13:45
@MexinaD @santoshmath Created a PR #2083 referencing this issue.

![screenshot 20](https://cloud.githubusercontent.com/assets/10477029/23823742/091add76-068f-11e7-8b51-a7d57ae1f87e.png)

**Comment by santoshmath** [comment] 2017-03-13 05:51
@mbj36 ,Is PR for this merged?

**Comment by mbj36** [comment] 2017-03-13 06:32
Not yet.  Will review today

**Comment by iamsk9** [comment] 2017-03-15 16:32
@mbj36 Created a new PR #2108

**Comment by mbj36** [comment] 2017-03-16 08:32
@santoshmath retest and close it

**Comment by santoshmath** [comment] 2017-03-16 10:22
Tested it on 16/3/2017 on new_reskin branch. This issue is resolved. @MexinaD , Please check

**Closed by santoshmath** 2017-03-16 10:22 UTC
Labels: bug, p1, reskin
