### ISSUE TITLE
Organization Settings Landing Page in Admin extends beyond borders of page

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#1759] opened 2016-12-27 17:07 UTC
It appears to be zoomed in too far. Should be of normal size and centered.

See https://demo.openmf.org/reskin/#/organization

<img width="1275" alt="screen shot 2016-12-27 at 9 06 25 am" src="https://cloud.githubusercontent.com/assets/823454/21504440/e54722e8-cc13-11e6-822c-f83f0a948adb.png">

vs
<img width="1269" alt="screen shot 2016-12-27 at 9 06 32 am" src="https://cloud.githubusercontent.com/assets/823454/21504446/ed7688e6-cc13-11e6-9882-d9c8a94f38a2.png">

**Comment by gkrishnan724** [comment] 2017-02-19 06:30
Hi @edcable  I am not able to reproduce this in localhost, but I see the issue exists only in the demo page is there a way to fix that?

**Comment by mbj36** [comment] 2017-02-21 15:07
@gkrishnan724 this issue existed in https://demo.openmf.org/reskin/#/ , now we have deployed it to https://demo.openmf.org/newbeta/#/organization in which it seems to be fixed. So closing the issue

**Closed** 2017-02-21 15:07 UTC
Labels: bug, gci, reskin
