### ISSUE TITLE
Return to top button not working properly in Products

### ISSUE THREAD

**Issue by shubhshrma** [openMF/community-app#2866] opened 2018-02-04 18:15 UTC
## Description
The return to top button inside Products is not scrolling to complete top of page and also doesn't function more than once.

## Steps to Reproduce
Go to:
1. Products> Loan Products> select any product > go to bottom and click ```top``` 
2. Products> Savings Products> select any product > go to bottom and click ```top```

## Settings
- Mifos X version: 17.07.01.RELEASE
- Browser used: Firefox 58.0.1 (64-bit) Ubuntu

## Screenshots, if any
![peek 2018-02-04 23-30](https://user-images.githubusercontent.com/20224346/35780684-36b15c72-0a05-11e8-8700-abdfa20e2b20.gif)

**Comment by mbj36** [comment] 2018-02-04 18:16
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

Possibly related issues are #2503 (View Journal Entries button does not work from individual transaction), and #2350 ( Previous and Next month calendar dates must be dimmed in selected month).

**Comment by shubhshrma** [comment] 2018-02-04 18:16
I'll work on this.

**Comment by anweshknayak** [comment] 2018-02-05 09:08
duplicate of #2777

**Comment by shubhshrma** [comment] 2018-02-05 11:03
@anweshknayak In #2777 you've mentioned pages where return to top button is not present  but in ```Products``` it is present but not working properly. I think these issues aren't duplicate.

**Comment by anweshknayak** [comment] 2018-02-05 11:04
#2742 then

**Comment by shubhshrma** [comment] 2018-02-05 11:12
Yes, closing as duplicate.

**Closed** 2018-02-05 11:12 UTC
Labels: bug, gsoc
