### ISSUE TITLE
Staff Assignment History alignment

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2833] opened 2018-01-19 09:49 UTC
**Steps to Reproduce**
Go to Center  >> More >> Staff Assignment History

**Expected Behavior**
Staff Assignment History should not overlap Release Version Link

![staff](https://user-images.githubusercontent.com/13551795/35152664-5b0612d0-fd34-11e7-88c5-0b7823578890.png)

**Comment by mbj36** [comment] 2018-01-19 09:49
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mbj36.

**Comment by ankit01ojha** [comment] 2018-01-19 13:04
@mbj36 duplicate of #2723

**Comment by ankit01ojha** [comment] 2018-01-19 13:05
@Agnessy , I have already created this issue and had sent the PR for this :)

**Comment by Agnessy** [comment] 2018-01-19 13:12
@ankit01ojha Thanks, Let me edit.

**Comment by ankit01ojha** [comment] 2018-02-23 21:18
@Agnessy are you working on this issue? If not, I would like to work on this.

**Comment by AgnessMeena** [comment] 2018-04-17 13:34
Hi, @ankit01ojha am not working on it,, go on with it.

**Closed** 2020-09-23 04:43 UTC
Labels: bug, design, p1_MifosRelease
