### ISSUE TITLE
Landing page Loading issues

### ISSUE THREAD

**Issue by VampireNaeem** [openMF/community-app#3122] opened 2019-10-17 12:00 UTC
The login page is taking so much time in loading, 

if we clear cache then it takes too long, often it crashes

**Comment by santoshconflux** [comment] 2019-10-22 05:14
@VampireNaeem , where did you try, locally or?

**Comment by VampireNaeem** [comment] 2019-10-22 06:58
> @VampireNaeem , where did you try, locally or?

Yeah locally and on Demo server too

**Comment by shivanshxyz** [comment] 2019-12-29 11:28
The local setup fetches the API from demo server so when the demo server remains down then the local setup doesn't work either.

**Comment by shivanshxyz** [comment] 2019-12-29 11:30
@VampireNaeem its not a bug so please close the issue

**Comment by VampireNaeem** [comment] 2021-03-05 08:41
this is not the bug

**Closed as completed** 2021-03-05 08:41 UTC
