### ISSUE TITLE
Can't Submit Single Row Data Table without Putting in Name for Second Column

### ISSUE THREAD

**Issue by edcable** [openMF/community-app#2954] opened 2018-05-12 14:46 UTC
## Description
Can't submit single row data table unless a column name is put in for second column. 

## Steps to Reproduce
Create a new data table and name the data table
Leave multi-row unchecked.

Add a row to the data table by filling in the fields and clicking the plus sign. 

## Expected Behaviour
Should be able to successfully submit data table. 

## Actual Behaviour

Can't submit data table because the field for Column Name in the Add Columns row is highlighted red, saying it's required. 

## Settings
Demo3 Server
Chrome
<img width="1142" alt="screen shot 2018-05-12 at 10 34 31 am" src="https://user-images.githubusercontent.com/823454/39958479-b049dc40-55d1-11e8-9157-5d522ecdb0ab.png">

**Comment by ShruthiRajaram** [comment] 2018-11-09 12:51
@santoshconflux it looks like duplicate of #2981. Kindly test and close.

**Comment by santoshconflux** [comment] 2018-11-12 07:04
@ShruthiRajaram , Yes. Closing this one.

**Closed as completed** 2018-12-14 07:31 UTC
Labels: bug, gsoc, Hacktoberfest, cg4w
