### ISSUE TITLE
[Mifos-User]- Unable to create or Add user and client in Mifos Multi-tenant

### ISSUE THREAD

**Issue by BalaVignesh18** [openMF/community-app#3084] opened 2019-02-11 10:28 UTC
## Settings

- Mifos X version: 
- Browser used:
- OS:

**Comment by BalaVignesh18** [comment] 2019-02-11 10:29
I have installed Mifos 18.03.01 and also created Multi-tenant , but unable to add user and client in Multi-tenant

**Comment by santoshconflux** [comment] 2019-02-22 03:32
I am not able to understand. Could you give some more details?

**Comment by fonlawrence** [comment] 2019-03-12 15:13
Please could you give the steps to reproduce for a start?

**Comment by SupreethSudhakaranMenon** [comment] 2019-03-14 11:22
![Select  Clients](https://user-images.githubusercontent.com/45706852/54352913-b8164d80-4678-11e9-8568-7dbcded71a6d.png)
![CreateClient](https://user-images.githubusercontent.com/45706852/54352921-c06e8880-4678-11e9-890a-58ecfd073573.png)
![Form](https://user-images.githubusercontent.com/45706852/54352929-c49aa600-4678-11e9-9382-d688a8ea86bd.png)

Select the "Clients" dropdown menu and select the first option "Clients" , this will redirect you to the page where you can view the clients and also a navigation bar where you have an option of creating new client , click on that option and you will be taken to a page where you can fill the details required.
I hope i have answered your questions @BalaVignesh18 
Below i have attached the screenshots which might help you.

**Comment by edcable** [comment] 2020-06-14 05:42
Closed as invalid. Not able to reproduce

**Closed as completed by edcable** 2020-06-14 05:42 UTC
Labels: bug, gci, gsoc
