### ISSUE TITLE
Not able to submit new loan application with the submitted date as current system date (today's date)

### ISSUE THREAD

**Issue by subsnrao** [openMF/community-app#3204] opened 2020-05-06 01:06 UTC
Observed in https://demo.mifos.io/#/createglaccount,
![image](https://user-images.githubusercontent.com/26272738/81130045-f600c000-8f63-11ea-999b-e299f441c03b.png)

**Comment by edcable** [comment] 2020-06-14 16:31
@subsnrao I'm not able to reproduce this issue on https://dev.mifos.io. Can you try reproducing it there? Same credentials as https://demo.mifos.io.

**Comment by bharathcgowda** [comment] 2021-05-01 08:50
closing this ticket as this issue doesnt exists

**Closed as completed by bharathcgowda** 2021-05-01 08:50 UTC
