### ISSUE TITLE
Reskin:"Events" details is not properly aligned in Manage Hooks

### ISSUE THREAD

**Issue by Agnessy** [openMF/community-app#2231] opened 2017-05-15 09:41 UTC
Go to System>Manage Hooks>Create Hook
After submit, The "Events" details is not properly aligned.  
Without Reskin
![mhh1](https://cloud.githubusercontent.com/assets/13551795/26051380/ab744dc4-396a-11e7-8096-e172c1b1bb86.png)
With Reskin
![mh2](https://cloud.githubusercontent.com/assets/13551795/26051487/03bc4a54-396b-11e7-8418-6a233c28372b.png)

**Comment by MexinaD** [comment] 2017-05-15 10:19
The issue is fixed at #2232

**Comment by mbj36** [comment] 2017-05-16 07:56
@santoshmath Retest and close it

**Closed** 2017-05-16 09:52 UTC
Labels: bug, design, gsoc, p2
