### ISSUE TITLE
I have managed to deploy Mifosx on ubuntu 22.04 sucessfuly on digitalocean but I cant seem to login into the app 

### ISSUE THREAD

**Issue by isaka254** [openMF/community-app#3551] opened 2024-09-21 22:40 UTC
## Description
The app loads sucessfully, tomcat is runnnig ok, maria db is running ok, I have checked other services are running ok issue is i just can login 

## Settings

- Mifos X version: 23.12.31 
- Browser used: Chrome
- OS: Linux Ubuntu 22.04 LTS

**Comment by ichux** [comment] 2024-09-22 10:34
There are many things you can try but then, you need to add more context to the information you sent:
1. open the network console before you login
2. check to see if there are errors before login
3. once you have that, then one can begin to zero in on what the issue is.

**Comment by francisguchie** [comment] 2024-09-22 10:59
@isaka254 
I strongly advise you to use the link below that provides the step by step guide to installing. Dont forget to look at the comments sections for issues you might be faced with that other users have been through already (i personally find them very helpful)
https://mifosforge.jira.com/wiki/spaces/docs/pages/85033021/Installing+Mifos+X

**Important points to Note**
If your desire is to install and use community-app User interface then please stick to mifos 21.07.02 on the link below 
https://mifosforge.jira.com/wiki/spaces/docs/pages/2824142857/Mifos+21.07.02+Installation+on+Tomcat-Ubuntu+18.04
Also please stick to the prerequisites mentioned at the top of the page, anything out of it might give you challenges 

If you desire to install versions above 21.07.02 then this community-app UI will be missing a number of functions (might not be consuming all APIs available today) and you might be faced with un-necessary errors. Looking at the image below you will see that the last update on this repository was about  2 years ago.
![image](https://github.com/user-attachments/assets/0840c80c-2111-4f1d-8ac5-a526091af239)

**So therefore note that, anything above MifosX 21.07.02 you will need to use the WebApp user interface here https://github.com/openMF/web-app** 

Above all, I strongly advise to keep all questions about installation on the installations guide.

Having said that, I think you will need to close this issue and repost this your questions or comments on the installation guide you will have chosen.

Please see image below of how many guides are available at the moment 
![image](https://github.com/user-attachments/assets/9cd63ebc-e84f-4d0f-a8b6-c59fd106debe)

**Comment by isaka254** [comment] 2024-09-22 14:02
Thank you for your advice in that case which is the most stable webapp and which link can I use I have also tried several docker images and I have encountered many challenges let me add that I am new to this

**Closed as completed** 2024-09-22 15:19 UTC
